using Frends.MySQL.ExecuteQuery.Definitions;
using MySqlConnector;
using Newtonsoft.Json.Linq;
using System;
using System.ComponentModel;
using System.Data;
using System.Globalization;
using System.Threading;
using System.Threading.Tasks;

namespace Frends.MySQL.ExecuteQuery;

/// <summary>
/// MySQL ExecuteQuery task.
/// </summary>
public static class MySQL
{
    /// <summary>
    /// Execute queries against the MySql database and return result of query in JToken.
    /// [Documentation](https://tasks.frends.com/tasks/frends-tasks/Frends.MySQL.ExecuteQuery)
    /// </summary>
    /// <param name="query">Query parameters</param>
    /// <param name="options">Options parameters</param>
    /// <param name="cancellationToken">Token generated by Frends to stop this task.</param>
    /// <returns>Object { bool Success, JToken ResultJtoken }</returns>
    public static async Task<Result> ExecuteQuery([PropertyTab] QueryInput query, [PropertyTab] Options options, CancellationToken cancellationToken)
    {
        try
        {
            using var conn = new MySqlConnection(query.ConnectionString);
            await conn.OpenAsync(cancellationToken).ConfigureAwait(false);
            cancellationToken.ThrowIfCancellationRequested();

            using var command = new MySqlCommand();
            command.Connection = conn;
            command.CommandType = CommandType.Text;
            command.CommandText = query.CommandText;
            if (query.Parameters != null)
            {
                command.CreateParameter();
                foreach (var parameter in query.Parameters)
                {
                    cancellationToken.ThrowIfCancellationRequested();
                    command.Parameters.Add(new MySqlParameter(parameter.Name, parameter.Value));
                }
            }
            command.CommandTimeout = options.TimeoutSeconds;

            Result result;

            // Execute command based on ExecuteType.
            switch (query.ExecuteType)
            {
                case ExecuteTypes.Auto:
                    // Auto-detect: Check if query returns data
                    {
                        var isolationLevel = GetIsolationLevel(options.MySqlTransactionIsolationLevel);
                        using var transaction = await conn.BeginTransactionAsync(isolationLevel, cancellationToken);
                        command.Transaction = transaction;

                        using (var reader = await command.ExecuteReaderAsync(cancellationToken))
                        {
                            // Check if the query returned any data (has columns)
                            if (reader.FieldCount > 0)
                            {
                                // Query returned data (SELECT)
                                result = new Result(true, reader.ToJson(cancellationToken));
                            }
                            else
                            {
                                // Query did not return data, use RecordsAffected
                                result = new Result(true, JToken.FromObject(reader.RecordsAffected));
                            }
                        } // Reader is disposed here

                        await transaction.CommitAsync(cancellationToken);
                    }
                    break;

                case ExecuteTypes.ExecuteReader:
                    // Explicitly return data
                    {
                        var isolationLevel = GetIsolationLevel(options.MySqlTransactionIsolationLevel);
                        using var transaction = await conn.BeginTransactionAsync(isolationLevel, cancellationToken);
                        command.Transaction = transaction;

                        using (var reader = await command.ExecuteReaderAsync(cancellationToken))
                        {
                            result = new Result(true, reader.ToJson(cancellationToken));
                        } // Reader is disposed here

                        await transaction.CommitAsync(cancellationToken);
                    }
                    break;

                case ExecuteTypes.NonQuery:
                    // Execute without returning data - use transaction
                    {
                        var isolationLevel = GetIsolationLevel(options.MySqlTransactionIsolationLevel);
                        using var transaction = await conn.BeginTransactionAsync(isolationLevel, cancellationToken);
                        command.Transaction = transaction;
                        var rows = await command.ExecuteNonQueryAsync(cancellationToken);
                        result = new Result(true, JToken.FromObject(rows));
                        await transaction.CommitAsync(cancellationToken);
                    }
                    break;

                default:
                    throw new ArgumentException($"Unsupported ExecuteType: {query.ExecuteType}");
            }

            return result;
        }
        catch (Exception ex)
        {
            throw new Exception(ex.Message);
        }
    }

    #region HelperMethods

    // Extension method for MySqlDataReader to read the data and return it as JToken.
    private static JToken ToJson(this MySqlDataReader reader, CancellationToken cancellationToken)
    {
        // Create JSON result.
        using (var writer = new JTokenWriter())
        {
            writer.Formatting = Newtonsoft.Json.Formatting.Indented;
            writer.Culture = CultureInfo.InvariantCulture;

            // Start array.
            writer.WriteStartArray();

            while (reader.Read())
            {
                cancellationToken.ThrowIfCancellationRequested();
                // Start row object.
                writer.WriteStartObject();
                for (var i = 0; i < reader.FieldCount; i++)
                {
                    // Add row element name.
                    writer.WritePropertyName(reader.GetName(i));

                    // Add row element value.
                    writer.WriteValue(reader.GetValue(i) ?? string.Empty);
                }

                // End row object.
                writer.WriteEndObject();
            }
            // End array.
            writer.WriteEndArray();

            return writer.Token;
        }
    }

    // Determine transaction isolation level from Options-class.
    private static IsolationLevel GetIsolationLevel(MySqlTransactionIsolationLevel level)
    {
        return level switch
        {
            MySqlTransactionIsolationLevel.ReadCommitted => IsolationLevel.ReadCommitted,
            MySqlTransactionIsolationLevel.ReadUncommitted => IsolationLevel.ReadUncommitted,
            MySqlTransactionIsolationLevel.RepeatableRead => IsolationLevel.RepeatableRead,
            MySqlTransactionIsolationLevel.Serializable => IsolationLevel.Serializable,
            _ => IsolationLevel.RepeatableRead,
        };
    }

    #endregion
}